name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    env:
      BUILD_CONFIG: Release
    name: Test and publish
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7

      - name: Install dependencies
        working-directory: src
        run: dotnet restore

      - name: Build
        working-directory: src
        run: dotnet build -c ${{ env.BUILD_CONFIG }} --no-restore -p:ContinuousIntegrationBuild=true

      - name: Test
        working-directory: src
        run: dotnet test -c ${{ env.BUILD_CONFIG }} --no-restore

      - name: Publish
        working-directory: src
        run: |
          dotnet pack -c ${{ env.BUILD_CONFIG }} --no-build
          dotnet nuget push --skip-duplicate Nethermind.Verkle/bin/${{ env.BUILD_CONFIG }}/*.nupkg -k ${{ secrets.NUGET_TEST_API_KEY }} -s https://apiint.nugettest.org/v3/index.json
